from django.urls import path
from .views import (
    MyAttendanceView,
    OverallAttendanceView,
    SubjectSummaryView,
    MonthlyAttendanceView,
    StudentListView,
    MarkAttendanceView,
    UpdateAttendanceView,
    SubjectListView,
    LoadAttendanceView,
    AdminDashboardView,
    AdminAttendanceListView,
    AdminAttendanceUpdateView,
    AdminAttendanceDeleteView,
    AdminAttendanceAnalyticsView,
    StudentAttendanceReportView,
    StaffPerformanceView,
    StaffListCreateView,
    StaffUpdateView,
    StaffStatusView,
    StaffDeleteView,
    LowAttendanceStudentsView
)

urlpatterns = [
    path(
        "my/",
        MyAttendanceView.as_view(),
        name="my-attendance",
    ),
    path(
        "overall/",
        OverallAttendanceView.as_view(),
        name="overall-attendance",
    ),
    path(
        "subject-summary/",
        SubjectSummaryView.as_view(),
        name="subject-summary",       
    ),
    path(
        "monthly/",
        MonthlyAttendanceView.as_view(),
        name="monthly-attendance",
    ),
    path(
        "students/",
        StudentListView.as_view(),
        name="student-list",
    ),
    path(
        "subjects/",
        SubjectListView.as_view(),
        name="subject-list",
    ),
    path(
        "mark/",
        MarkAttendanceView.as_view(),
        name="mark-attendance",
    ),
    path(
        "update/<int:pk>/",
        UpdateAttendanceView.as_view(),
        name="update-attendance",
    ),
    path(
        "load/",
        LoadAttendanceView.as_view(),
        name="load-attendance",
    ),
    path(
        "admin/dashboard/",
        AdminDashboardView.as_view(),
        name="admin-dashboard",
    ),
    path(
        "admin/attendance/",
        AdminAttendanceListView.as_view(),
        name="admin-attendance-list",
    ),
    path(
        "admin/attendance/<int:pk>/",
        AdminAttendanceUpdateView.as_view(),
        name="admin-attendance-update",
    ),
    path(
        "admin/attendance/<int:pk>/delete/",
        AdminAttendanceDeleteView.as_view(),
        name="admin-attendance-delete",
    ),
    path(
        "admin/analytics/",
        AdminAttendanceAnalyticsView.as_view(),
        name="admin-attendance-analytics",
    ),
    path(
        "admin/student-report/<int:student_id>/",
        StudentAttendanceReportView.as_view(),
        name="student-attendance-report",
    ),
    path(
        "admin/staff-performance/",
        StaffPerformanceView.as_view(),
        name="staff-performance",
    ),
    path(
        "admin/staff/",
        StaffListCreateView.as_view(),
        name="staff-list-create",
    ),
    path(
        "admin/staff/<int:pk>/",
        StaffUpdateView.as_view(),
        name="staff-update",
    ),
    path(
        "admin/staff/<int:pk>/status/",
        StaffStatusView.as_view(),
        name="staff-status",
    ),
    path(
        "admin/staff/<int:pk>/delete/",
        StaffDeleteView.as_view(),
        name="staff-delete",
    ),
    path(
        "admin/low-attendance/",
        LowAttendanceStudentsView.as_view(),
        name="low-attendance-students",
    ),
]

