from django.urls import path
from .views import (
    MyAttendanceView,
    OverallAttendanceView,
    SubjectSummaryView,
    MonthlyAttendanceView,
    StudentListView,
    MarkAttendanceView,
    UpdateAttendanceView,
    SubjectListView,
    LoadAttendanceView,
    AdminDashboardView,
    AdminAttendanceListView
)

path

urlpatterns = [
    path(
        "my/",
        MyAttendanceView.as_view(),
        name="my-attendance",
    ),
    path(
        "overall/",
        OverallAttendanceView.as_view(),
        name="overall-attendance",
    ),
    path(
        "subject-summary/",
        SubjectSummaryView.as_view(),
        name="subject-summary",       
    ),
    path(
        "monthly/",
        MonthlyAttendanceView.as_view(),
        name="monthly-attendance",
    ),
    path(
        "students/",
        StudentListView.as_view(),
        name="student-list",
    ),
    path(
        "subjects/",
        SubjectListView.as_view(),
        name="subject-list",
    ),
    path(
        "mark/",
        MarkAttendanceView.as_view(),
        name="mark-attendance",
    ),
    path(
        "update/<int:pk>/",
        UpdateAttendanceView.as_view(),
        name="update-attendance",
    ),
    path(
        "load/",
        LoadAttendanceView.as_view(),
        name="load-attendance",
    ),
    path(
        "admin/dashboard/",
        AdminDashboardView.as_view(),
        name="admin-dashboard",
    ),
    path(
        "admin/attendance/",
        AdminAttendanceListView.as_view(),
        name="admin-attendance-list",
    ),
]

